{{- range $key, $value := (getenv "ENVS" | yaml) -}}
export {{ $key }} := {{ $value }}
{{ end }}

{{- $test_targets_escaped := dict -}}

{{- range $test_target := (getenv "TEST_TARGETS" | yamlArray) -}}

{{- $p := "" -}}
{{- if eq $test_target "." -}}
{{- $p = "./..." -}}
{{- else -}}
{{- $p = printf "./%s/..." $test_target -}}
{{- end -}}

{{- $test_targets_escaped = merge $test_targets_escaped (dict (printf "test_%s" (strings.ReplaceAll "/" "_" $test_target)) $p) -}}

{{- end -}}

{{- $target := (getenv "TARGET") }}
{{- $target_escaped := strings.ReplaceAll "/" "_" $target }}
{{- $bin := filepath.Base $target }}
all: {{ $target_escaped }} {{ join (keys $test_targets_escaped) " " }}

{{ $target_escaped }}:
	cd {{ $target }} && go build .
	cp {{ $target }}/{{ $bin }} .

{{ range $key, $value := $test_targets_escaped -}}
{{ $key }}:
	go test {{ $value }}
{{ end }}
