{{- $targets := (getenv "TARGETS" | yamlArray) -}}

all: tests

tests: {{ join $targets " " | strings.ReplaceAll "/" "_" }}

{{ range $_, $target := $targets }}
{{ strings.ReplaceAll "/" "_" $target }}:
	cd {{ $target }} && go test ./...
{{ end }}
