#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

export KUBE_TIMEOUT='-timeout=1200s'

make test-integration WHAT=./vendor/k8s.io/apiextensions-apiserver/test/integration/...
make test-integration WHAT=./test/integration/apimachinery/...
make test-integration WHAT=./test/integration/apiserver/...
make test-integration WHAT=./test/integration/auth/...
make test-integration WHAT=./test/integration/certificates/...
make test-integration WHAT=./test/integration/client/...
make test-integration WHAT=./test/integration/configmap/...
make test-integration WHAT=./test/integration/cronjob/...
make test-integration WHAT=./test/integration/daemonset/...
make test-integration WHAT=./test/integration/defaulttolerationseconds/...
make test-integration WHAT=./test/integration/deployment/...
make test-integration WHAT=./test/integration/disruption/...
make test-integration WHAT=./test/integration/dryrun/...
make test-integration WHAT=./test/integration/dualstack/...
make test-integration WHAT=./test/integration/endpoints/...
make test-integration WHAT=./test/integration/endpointslice/...
make test-integration WHAT=./test/integration/etcd/...
make test-integration WHAT=./test/integration/events/...
make test-integration WHAT=./test/integration/evictions/...
make test-integration WHAT=./test/integration/examples/...
make test-integration WHAT=./test/integration/garbagecollector/...
make test-integration WHAT=./test/integration/ipamperf/...
make test-integration WHAT=./test/integration/kubelet/...
make test-integration WHAT=./test/integration/master/...
make test-integration WHAT=./test/integration/metrics/...
make test-integration WHAT=./test/integration/namespace/...
make test-integration WHAT=./test/integration/node/...
make test-integration WHAT=./test/integration/objectmeta/...
make test-integration WHAT=./test/integration/openshift/...
make test-integration WHAT=./test/integration/pods/...
make test-integration WHAT=./test/integration/quota/...
make test-integration WHAT=./test/integration/replicaset/...
make test-integration WHAT=./test/integration/replicationcontroller/...
make test-integration WHAT=./test/integration/scale/...
make test-integration WHAT=./test/integration/scheduler/...
make test-integration WHAT=./test/integration/scheduler_perf/...
make test-integration WHAT=./test/integration/secrets/...
make test-integration WHAT=./test/integration/serviceaccount/...
make test-integration WHAT=./test/integration/serving/...
make test-integration WHAT=./test/integration/statefulset/...
make test-integration WHAT=./test/integration/storageclasses/...
make test-integration WHAT=./test/integration/storageversion/...
make test-integration WHAT=./test/integration/tls/...
make test-integration WHAT=./test/integration/ttlcontroller/...
make test-integration WHAT=./test/integration/volume/...
make test-integration WHAT=./test/integration/volumescheduling/...
