{{- $targets := (getenv "TARGETS" | yamlArray) -}}
all: {{ join $targets " " | strings.ReplaceAll "/" "_" }}

{{ range $_, $target := $targets }}
{{- strings.ReplaceAll "/" "_" $target -}}:
	go test ./{{ $target }}/...

{{ end -}}