POLYREPO_DEST_ROOT_DIR   := $(HOME)/Projects/masters/polyrepo

KUBERNETES_POLYREPO_BINARY_COMPONENTS_SUBDIRS_TARGETS := $(addprefix _polyrepo_create_binary_component_subdir_,$(KUBERNETES_BINARY_COMPONENTS))
KUBERNETES_POLYREPO_BINARY_COMPONENTS_MIGRATE_TARGETS := $(addprefix _migrate_binary_component_to_polyrepo_,$(KUBERNETES_BINARY_COMPONENTS))

KUBERNETES_POLYREPO_INTEGRATION_TESTS_SUBDIRS_TARGETS := $(addprefix _polyrepo_create_integration_test_subdir_,$(KUBERNETES_INTEGRATION_TESTS))
KUBERNETES_POLYREPO_INTEGRATION_TESTS_MIGRATE_TARGETS := $(addprefix _migrate_integration_test_to_polyrepo_,$(KUBERNETES_INTEGRATION_TESTS))

KUBERNETES_POLYREPO_APIS_SUBDIRS_TARGETS := $(addprefix _polyrepo_create_api_subdir_,$(KUBERNETES_APIS))
KUBERNETES_POLYREPO_APIS_MIGRATE_TARGETS := $(addprefix _migrate_api_to_polyrepo_,$(KUBERNETES_APIS))

KUBERNETES_POLYREPO_PLUGINS_SUBDIRS_TARGETS := $(addprefix _polyrepo_create_plugin_subdir_,$(KUBERNETES_PLUGINS))
KUBERNETES_POLYREPO_PLUGINS_MIGRATE_TARGETS := $(addprefix _migrate_plugin_to_polyrepo_,$(KUBERNETES_PLUGINS))

KUBERNETES_POLYREPO_STAGING_SUBDIRS_TARGETS := $(addprefix _polyrepo_create_staging_subdir_,$(KUBERNETES_STAGING))
KUBERNETES_POLYREPO_STAGING_MIGRATE_TARGETS := $(addprefix _migrate_staging_to_polyrepo_,$(KUBERNETES_STAGING))

KUBERNETES_POLYREPO_E2E_TESTS_SUBDIRS_TARGETS := $(addprefix _polyrepo_create_e2e_test_subdir_,$(KUBERNETES_E2E_TESTS))
KUBERNETES_POLYREPO_E2E_TESTS_MIGRATE_TARGETS := $(addprefix _migrate_e2e_test_to_polyrepo_,$(KUBERNETES_E2E_TESTS))

polyrepo_create_binary_components_subdirs: $(KUBERNETES_POLYREPO_BINARY_COMPONENTS_SUBDIRS_TARGETS)
polyrepo_create_integration_tests_subdirs: $(KUBERNETES_POLYREPO_INTEGRATION_TESTS_SUBDIRS_TARGETS)
polyrepo_create_apis_subdirs: $(KUBERNETES_POLYREPO_APIS_SUBDIRS_TARGETS)
polyrepo_create_plugins_subdirs: $(KUBERNETES_POLYREPO_PLUGINS_SUBDIRS_TARGETS)
polyrepo_create_staging_subdirs: $(KUBERNETES_POLYREPO_STAGING_SUBDIRS_TARGETS)
polyrepo_create_e2e_tests_subdirs: $(KUBERNETES_POLYREPO_E2E_TESTS_SUBDIRS_TARGETS)

polyrepo_create_all_subdirs: polyrepo_create_binary_components_subdirs
polyrepo_create_all_subdirs: polyrepo_create_integration_tests_subdirs
polyrepo_create_all_subdirs: polyrepo_create_apis_subdirs
polyrepo_create_all_subdirs: polyrepo_create_plugins_subdirs
polyrepo_create_all_subdirs: polyrepo_create_staging_subdirs
polyrepo_create_all_subdirs: polyrepo_create_e2e_tests_subdirs

migrate_binary_components_to_polyrepo: $(KUBERNETES_POLYREPO_BINARY_COMPONENTS_MIGRATE_TARGETS)
migrate_integration_tests_to_polyrepo: $(KUBERNETES_POLYREPO_INTEGRATION_TESTS_MIGRATE_TARGETS)
migrate_apis_to_polyrepo: $(KUBERNETES_POLYREPO_APIS_MIGRATE_TARGETS)
migrate_plugins_to_polyrepo: $(KUBERNETES_POLYREPO_PLUGINS_MIGRATE_TARGETS)
migrate_staging_to_polyrepo: $(KUBERNETES_POLYREPO_STAGING_MIGRATE_TARGETS)
migrate_e2e_tests_to_polyrepo: $(KUBERNETES_POLYREPO_E2E_TESTS_MIGRATE_TARGETS)

migrate_all_to_polyrepo: migrate_binary_components_to_polyrepo
migrate_all_to_polyrepo: migrate_integration_tests_to_polyrepo
migrate_all_to_polyrepo: migrate_apis_to_polyrepo
migrate_all_to_polyrepo: migrate_plugins_to_polyrepo
migrate_all_to_polyrepo: migrate_staging_to_polyrepo
migrate_all_to_polyrepo: migrate_e2e_tests_to_polyrepo

POLYREPO_BINARY_COMPONENTS_RELATIVE_DIR := binary_components
POLYREPO_INTEGRATION_TESTS_RELATIVE_DIR := integration_tests
POLYREPO_APIS_RELATIVE_DIR              := apis
POLYREPO_PLUGINS_RELATIVE_DIR           := plugins
POLYREPO_STAGING_RELATIVE_DIR           := staging
POLYREPO_E2E_TESTS_RELATIVE_DIR         := e2e_tests

POLYREPO_BINARY_COMPONENTS_DEST_ROOT_DIR := $(POLYREPO_DEST_ROOT_DIR)/$(POLYREPO_BINARY_COMPONENTS_RELATIVE_DIR)
POLYREPO_INTEGRATION_TESTS_DEST_ROOT_DIR := $(POLYREPO_DEST_ROOT_DIR)/$(POLYREPO_INTEGRATION_TESTS_RELATIVE_DIR)
POLYREPO_APIS_DEST_ROOT_DIR              := $(POLYREPO_DEST_ROOT_DIR)/$(POLYREPO_APIS_RELATIVE_DIR)
POLYREPO_PLUGINS_DEST_ROOT_DIR           := $(POLYREPO_DEST_ROOT_DIR)/$(POLYREPO_PLUGINS_RELATIVE_DIR)
POLYREPO_STAGING_DEST_ROOT_DIR           := $(POLYREPO_DEST_ROOT_DIR)/$(POLYREPO_STAGING_RELATIVE_DIR)
POLYREPO_E2E_TESTS_DEST_ROOT_DIR         := $(POLYREPO_DEST_ROOT_DIR)/$(POLYREPO_E2E_TESTS_RELATIVE_DIR)

clean_polyrepo:
	rm -rf $(POLYREPO_DEST_ROOT_DIR)

_polyrepo_create_binary_component_subdir_%:
	mkdir -p $(POLYREPO_BINARY_COMPONENTS_DEST_ROOT_DIR)/$(*)

_polyrepo_create_integration_test_subdir_%:
	mkdir -p $(POLYREPO_INTEGRATION_TESTS_DEST_ROOT_DIR)/$(*)

_polyrepo_create_api_subdir_%:
	mkdir -p $(POLYREPO_APIS_DEST_ROOT_DIR)/$(*)

_polyrepo_create_plugin_subdir_%:
	mkdir -p $(POLYREPO_PLUGINS_DEST_ROOT_DIR)/$(*)

_polyrepo_create_staging_subdir_%:
	mkdir -p $(POLYREPO_STAGING_DEST_ROOT_DIR)/$(*)

_polyrepo_create_e2e_test_subdir_%:
	mkdir -p $(POLYREPO_E2E_TESTS_DEST_ROOT_DIR)/$(*)

_polyrepo_migrate_binary_component_common_%:
	migrators_polyrepo/whisky-on-ice.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$($(*)_RELATIVE_SUBPATH) \
		$(POLYREPO_BINARY_COMPONENTS_DEST_ROOT_DIR)/$(*)

_polyrepo_migrate_binary_component_common_apiextensions-apiserver:
	migrators_polyrepo/whisky-on-rocks.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$(apiextensions-apiserver_RELATIVE_SUBPATH) \
		$(POLYREPO_BINARY_COMPONENTS_DEST_ROOT_DIR)/apiextensions-apiserver

_polyrepo_migrate_binary_component_common_kube-aggregator:
	migrators_polyrepo/whisky-on-rocks.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$(kube-aggregator_RELATIVE_SUBPATH) \
		$(POLYREPO_BINARY_COMPONENTS_DEST_ROOT_DIR)/kube-aggregator

_polyrepo_migrate_integration_test_common_%:
	migrators_polyrepo/whisky-on-ice.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		test/integration/$(*) \
		$(POLYREPO_INTEGRATION_TESTS_DEST_ROOT_DIR)/$(*)

_polyrepo_migrate_integration_test_common_apiextensions-apiserver:
	migrators_polyrepo/whisky-on-rocks.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$(apiextensions-apiserver_RELATIVE_SUBPATH)/test/integration \
		$(POLYREPO_INTEGRATION_TESTS_DEST_ROOT_DIR)/apiextensions-apiserver

_polyrepo_migrate_api_common_%:
	migrators_polyrepo/whisky-on-ice.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		pkg/$(*) \
		$(POLYREPO_APIS_DEST_ROOT_DIR)/$(*)

_polyrepo_migrate_plugin_common_%:
	migrators_polyrepo/whisky-on-ice.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		plugin/pkg/$(*) \
		$(POLYREPO_PLUGINS_DEST_ROOT_DIR)/$(*)

_polyrepo_migrate_staging_common_%:
	migrators_polyrepo/whisky-on-rocks.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		staging/src/k8s.io/$(*) \
		$(POLYREPO_STAGING_DEST_ROOT_DIR)/$(*)

_migrate_binary_component_to_polyrepo_%: _polyrepo_create_binary_component_subdir_% _polyrepo_migrate_binary_component_common_%
	migrators_polyrepo/binary_components/$(*).sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$($(*)_RELATIVE_SUBPATH) \
		$(POLYREPO_BINARY_COMPONENTS_DEST_ROOT_DIR)/$(*)

_migrate_integration_test_to_polyrepo_%: _polyrepo_create_integration_test_subdir_% _polyrepo_migrate_integration_test_common_%
	migrators_polyrepo/integration_tests/$(*).sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		test/integration/$(*) \
		$(POLYREPO_INTEGRATION_TESTS_DEST_ROOT_DIR)/$(*)

_migrate_integration_test_to_polyrepo_apiextensions-apiserver: _polyrepo_migrate_integration_test_common_apiextensions-apiserver
_migrate_integration_test_to_polyrepo_apiextensions-apiserver: _polyrepo_create_integration_test_subdir_apiextensions-apiserver
	migrators_polyrepo/integration_tests/apiextensions-apiserver.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$(apiextensions-apiserver_RELATIVE_SUBPATH)/test/integration \
		$(POLYREPO_INTEGRATION_TESTS_DEST_ROOT_DIR)/apiextensions-apiserver

_migrate_api_to_polyrepo_%: _polyrepo_create_api_subdir_% _polyrepo_migrate_api_common_%
	migrators_polyrepo/apis/$(*).sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		pkg/$(*) \
		$(POLYREPO_APIS_DEST_ROOT_DIR)/$(*)

_migrate_plugin_to_polyrepo_%: _polyrepo_create_plugin_subdir_% _polyrepo_migrate_plugin_common_%
	migrators_polyrepo/plugins/$(*).sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		plugin/pkg/$(*) \
		$(POLYREPO_PLUGINS_DEST_ROOT_DIR)/$(*)

_migrate_staging_to_polyrepo_%: _polyrepo_create_staging_subdir_% _polyrepo_migrate_staging_common_%
	migrators_polyrepo/staging/$(*).sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		staging/src/k8s.io/$(*) \
		$(POLYREPO_STAGING_DEST_ROOT_DIR)/$(*)

_migrate_e2e_test_to_polyrepo_cmd: _polyrepo_create_e2e_test_subdir_cmd
_migrate_e2e_test_to_polyrepo_cmd:
	migrators_polyrepo/e2e_tests/cmd.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$(POLYREPO_E2E_TESTS_DEST_ROOT_DIR)/cmd

_migrate_e2e_test_to_polyrepo_cluster: _polyrepo_create_e2e_test_subdir_cluster
_migrate_e2e_test_to_polyrepo_cluster:
	migrators_polyrepo/e2e_tests/cluster.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$(POLYREPO_E2E_TESTS_DEST_ROOT_DIR)/cluster

KUBERNETES_BINARY_COMPONENTS_POLYREPO_ADJ_FILE_TARGETS := $(addprefix _construct_binary_component_polyrepo_adj_file_,$(KUBERNETES_BINARY_COMPONENTS))
KUBERNETES_INTEGRATION_TESTS_POLYREPO_ADJ_FILE_TARGETS := $(addprefix _construct_integration_test_polyrepo_adj_file_,$(KUBERNETES_INTEGRATION_TESTS))
KUBERNETES_APIS_POLYREPO_ADJ_FILE_TARGETS              := $(addprefix _construct_api_polyrepo_adj_file_,$(KUBERNETES_APIS))
KUBERNETES_PLUGINS_POLYREPO_ADJ_FILE_TARGETS           := $(addprefix _construct_plugin_polyrepo_adj_file_,$(KUBERNETES_PLUGINS))
KUBERNETES_STAGING_POLYREPO_ADJ_FILE_TARGETS           := $(addprefix _construct_staging_polyrepo_adj_file_,$(KUBERNETES_STAGING))

construct_binary_components_polyrepo_adj_files: $(KUBERNETES_BINARY_COMPONENTS_POLYREPO_ADJ_FILE_TARGETS)
construct_integration_tests_polyrepo_adj_files: $(KUBERNETES_INTEGRATION_TESTS_POLYREPO_ADJ_FILE_TARGETS)
construct_apis_polyrepo_adj_files: $(KUBERNETES_APIS_POLYREPO_ADJ_FILE_TARGETS)
construct_plugins_polyrepo_adj_files: $(KUBERNETES_PLUGINS_POLYREPO_ADJ_FILE_TARGETS)
construct_staging_polyrepo_adj_files: $(KUBERNETES_STAGING_POLYREPO_ADJ_FILE_TARGETS)

POLYREPO_ADJ_FILE_MERGED_PATH               := $(POLYREPO_DEST_ROOT_DIR)/$(ADJ_FILE_MERGED_NAME)
POLYREPO_AGGR_ADJ_FILE_MERGED_PATH          := $(POLYREPO_DEST_ROOT_DIR)/$(AGGR_ADJ_FILE_MERGED_NAME)
POLYREPO_FILTERED_AGGR_ADJ_FILE_MERGED_PATH := $(POLYREPO_DEST_ROOT_DIR)/$(FILTERED_AGGR_ADJ_FILE_MERGED_NAME)

_construct_binary_component_polyrepo_adj_file_%:
	./adj.sh \
		$(POLYREPO_BINARY_COMPONENTS_DEST_ROOT_DIR)/$(*) \
		$($(*)_RELATIVE_SUBPATH) \
		$(ADJ_FILE_NAME)

_construct_integration_test_polyrepo_adj_file_%:
	./adj.sh \
		$(POLYREPO_INTEGRATION_TESTS_DEST_ROOT_DIR)/$(*) \
		test/integration/$(*) \
		$(ADJ_FILE_NAME)

_construct_integration_test_polyrepo_adj_file_apiextensions-apiserver:
	./adj.sh \
		$(POLYREPO_INTEGRATION_TESTS_DEST_ROOT_DIR)/apiextensions-apiserver \
		$(apiextensions-apiserver_RELATIVE_SUBPATH)/test/integration \
		$(ADJ_FILE_NAME)

_construct_api_polyrepo_adj_file_%:
	./adj.sh \
		$(POLYREPO_APIS_DEST_ROOT_DIR)/$(*) \
		pkg/$(*) \
		$(ADJ_FILE_NAME)

_construct_plugin_polyrepo_adj_file_%:
	./adj.sh \
		$(POLYREPO_PLUGINS_DEST_ROOT_DIR)/$(*) \
		plugin/pkg/$(*) \
		$(ADJ_FILE_NAME)

_construct_staging_polyrepo_adj_file_%:
	./adj.sh \
		$(POLYREPO_STAGING_DEST_ROOT_DIR)/$(*) \
		staging/src/k8s.io/$(*) \
		$(ADJ_FILE_NAME)

construct_all_polyrepo_adj_files: construct_binary_components_polyrepo_adj_files
construct_all_polyrepo_adj_files: construct_integration_tests_polyrepo_adj_files
construct_all_polyrepo_adj_files: construct_apis_polyrepo_adj_files
construct_all_polyrepo_adj_files: construct_plugins_polyrepo_adj_files
construct_all_polyrepo_adj_files: construct_staging_polyrepo_adj_files

polyrepo_aggr_import_paths:
	find $(POLYREPO_DEST_ROOT_DIR) -maxdepth 3 -name "$(ADJ_FILE_NAME)" | xargs cat | sort > $(POLYREPO_ADJ_FILE_MERGED_PATH)
	$(VENV_PATH)/bin/python ./polyrepo_aggr_import_paths.py $(POLYREPO_ADJ_FILE_MERGED_PATH) $(POLYREPO_AGGR_ADJ_FILE_MERGED_PATH)

polyrepo_filter_import_paths:
	$(VENV_PATH)/bin/python \
		./polyrepo_filter_import_paths.py \
		$(POLYREPO_BINARY_COMPONENTS_DEST_ROOT_DIR) \
		$(POLYREPO_INTEGRATION_TESTS_DEST_ROOT_DIR) \
		$(POLYREPO_APIS_DEST_ROOT_DIR) \
		$(POLYREPO_PLUGINS_DEST_ROOT_DIR) \
		$(POLYREPO_STAGING_DEST_ROOT_DIR) \
		$(POLYREPO_AGGR_ADJ_FILE_MERGED_PATH) \
		$(POLYREPO_FILTERED_AGGR_ADJ_FILE_MERGED_PATH)

polyrepo_construct_edge_file: construct_all_polyrepo_adj_files
polyrepo_construct_edge_file: polyrepo_aggr_import_paths
polyrepo_construct_edge_file: polyrepo_filter_import_paths

polyrepo_make_all:
	./make-all.sh $(POLYREPO_DEST_ROOT_DIR)

POLYREPO_GIT_SERVER_REPOS_PREFIX  := http://$(GIT_SERVER_LISTEN_HOST):$(GIT_SERVER_LISTEN_PORT)
POLYREPO_GOCD_YAMLS_RELATIVE_DIR  := gocd_yamls
POLYREPO_GOCD_YAMLS_DEST_ROOT_DIR := $(POLYREPO_DEST_ROOT_DIR)/$(POLYREPO_GOCD_YAMLS_RELATIVE_DIR)

create_polyrepo_gocd_yamls_subdir:
	mkdir -p $(POLYREPO_GOCD_YAMLS_DEST_ROOT_DIR)

construct_polyrepo_gocd_yaml_files: create_polyrepo_gocd_yamls_subdir
	$(VENV_PATH)/bin/python \
		./polyrepo_gen_gocs_yamls.py \
		$(POLYREPO_BINARY_COMPONENTS_RELATIVE_DIR) \
		$(POLYREPO_INTEGRATION_TESTS_RELATIVE_DIR) \
		$(POLYREPO_APIS_RELATIVE_DIR) \
		$(POLYREPO_PLUGINS_RELATIVE_DIR) \
		$(POLYREPO_STAGING_RELATIVE_DIR) \
		$(POLYREPO_E2E_TESTS_RELATIVE_DIR) \
		$(POLYREPO_FILTERED_AGGR_ADJ_FILE_MERGED_PATH) \
		$(POLYREPO_GIT_SERVER_REPOS_PREFIX) \
		$(POLYREPO_GOCD_YAMLS_DEST_ROOT_DIR)

polyrepo_e2e_cmd_bootstrap:
	e2e_bootstrap/cmd_bootstrap.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$(POLYREPO_E2E_TESTS_DEST_ROOT_DIR)/cmd

polyrepo_e2e_cluster_bootstrap:
	e2e_bootstrap/cluster_bootstrap.sh \
		$(KUBERNETES_REPO_ROOT_DIR) \
		$(POLYREPO_E2E_TESTS_DEST_ROOT_DIR)/cluster
