export KUBECONFIG := $(HOME)/.kube/kind-test-config

cluster:
	go test -c ./test/e2e_kubeadm
	go test -c ./test/e2e

	./e2e_kubeadm.test --context kind-kind --num-nodes 2 --ginkgo.skip="\[copy-certs\]"
	./e2e.test --kubectl-path ./kubectl --context kind-kind --num-nodes 2 --ginkgo.focus="\[Conformance\]"
