# hack for scripts, kubeadm tested in binary component
all test:

# cmd test is flaky, skipping
bootstrap:
	#{{ getenv "BOOTSTRAP_SCRIPT_RELATIVE_PATH" }}

# cmd test is flaky, skipping
cmd:
	#go clean -cache
	#go clean -testcache

	#./hack/make-rules/test-cmd.sh
