FROM gocd/gocd-server:v21.2.0

COPY ./cruise-config.xml /godata/config/cruise-config.xml

USER root

RUN chown -R go:root /godata

USER go

RUN mkdir -p /go-working-dir/analytics-assets \
 && cd /go-working-dir/analytics-assets \
 && curl -fsSLO https://code.highcharts.com/6.1.3/modules/no-data-to-display.src.js \
 && curl -fsSLO https://code.highcharts.com/6.1.3/modules/xrange.src.js \
 && curl -fsSLO https://code.highcharts.com/6.1.3/highcharts.src.js
