{{- $parallelism := getenv "PARALLELISM" "1" -}}
{{- $timeout := getenv "TIMEOUT" "600" -}}

{{- $targets := (getenv "TARGETS" | yamlArray) -}}
all: {{ join $targets " " | strings.ReplaceAll "/" "_" }}
{{ range $_, $target := $targets }}
{{ strings.ReplaceAll "/" "_" $target }}:
	go clean -cache
	go clean -testcache

	cd {{ $target }} && go test \
		-p {{ $parallelism }} \
		-timeout {{ $timeout }}s \
		./...
{{ end }}
