{{- $parallelism := getenv "PARALLELISM" "1" -}}
{{- $timeout := getenv "TIMEOUT" "300" -}}

{{- $target := (getenv "TARGET") -}}
{{- $ldflags := join (getenv "BUILD_FLAGS" "[]" | yamlArray) " " -}}
{{- $bin := filepath.Base $target -}}

{{- $test_targets_escaped := dict -}}

{{- range $test_target := (getenv "TEST_TARGETS" "[]" | yamlArray) -}}
{{- $test_targets_escaped = merge $test_targets_escaped (dict (printf "test_%s" (strings.ReplaceAll "/" "_" $test_target)) $test_target) -}}
{{- end -}}

{{ if $ldflags }}export GOLDFLAGS := {{ $ldflags }}{{ end }}

all: build tests

build:
	hack/make-rules/build.sh {{ $target }}

	cp ./_output/bin/{{ $bin }} .

tests: {{ join (keys $test_targets_escaped) " " }}

{{ range $key, $value := $test_targets_escaped }}
{{ $key }}:
	cd {{ $value }} && go test \
		-p {{ $parallelism }} \
		-timeout {{ $timeout }}s \
		./...
{{ end }}

{{ range $key, $value := (getenv "ENVS" | yaml) }}
export {{ $key }} := {{ $value }}
{{ end }}
